name: Rust

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Windows dependencies
        if: startsWith(matrix.os,'windows')
        run: |
          choco install -y llvm
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
